import json

notebook = {
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# Solar Flare Forecaster (Nowcasting & Forecasting)\n",
        "\n",
        "**Problem Statement:** Build an automated algorithmic pipeline that uses the combined time-series data from Aditya-L1's SoLEXS and HEL1OS payloads to detect (nowcast) or predict (forecast) solar flares.\n",
        "\n",
        "### Instructions for Judges:\n",
        "1. Upload all the extracted SoLEXS `.lc.gz` and HEL1OS `.fits` data files to the Colab environment.\n",
        "2. Run all cells.\n",
        "3. Download the generated `flare_alerts.json` to plug into the React Native mobile dashboard."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "!pip install astropy pandas numpy scikit-learn"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Phase 1: Multi-Day Data Fusion & Feature Engineering"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "import os\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "from astropy.io import fits\n",
        "from datetime import datetime, timedelta\n",
        "\n",
        "def timestamp2datetime(time_arr, ref_date=datetime(2023, 1, 1)):\n",
        "    return [ref_date + timedelta(seconds=float(t)) for t in time_arr]\n",
        "\n",
        "def load_solexs(file_path):\n",
        "    with fits.open(file_path) as hdul:\n",
        "        data = hdul[1].data\n",
        "        time_col = data['TIME']\n",
        "        counts_col = data['COUNTS']\n",
        "        # TIME is Unix timestamp (seconds since 1970-01-01)\n",
        "        times = pd.to_datetime(np.array(time_col, dtype=np.float64), unit='s', utc=True).tz_localize(None)\n",
        "        counts_np = np.array(counts_col, dtype=np.float64)\n",
        "        df = pd.DataFrame({'time': times, 'soft_flux': counts_np})\n",
        "    return df\n",

        "\n",
        "def load_hel1os(file_path):\n",
        "    # HEL1OS uses MJD for time and CTR for count rate (not TIME/COUNTS)\n",
        "    # Extension 5 = broadband 1.8-90 keV (best for flare detection)\n",
        "    from astropy.time import Time\n",
        "    with fits.open(file_path) as hdul:\n",
        "        ext_idx = 5 if len(hdul) > 5 else 1\n",
        "        data = hdul[ext_idx].data\n",
        "        mjd_col = data['MJD']\n",
        "        ctr_col = data['CTR']\n",
        "        times = Time(mjd_col, format='mjd').to_datetime()\n",
        "        ctr_np = np.array(ctr_col, dtype=np.float64)\n",
        "        df = pd.DataFrame({'time': times, 'hard_flux': ctr_np})\n",
        "    return df\n",
        "\n",
        "print('Loading entire dataset directory...')\n",
        "data_dir = '.'\n",
        "solexs_files = sorted([f for f in os.listdir(data_dir) if f.endswith('.lc.gz')])\n",
        "hel1os_files = sorted([f for f in os.listdir(data_dir) if f.endswith('.fits') and 'lightcurve' in f])\n",
        "\n",
        "print(f'Found {len(solexs_files)} SoLEXS files and {len(hel1os_files)} HEL1OS files')\n",
        "\n",
        "solexs_dfs, hel1os_dfs = [], []\n",
        "for f in solexs_files:\n",
        "    try:\n",
        "        solexs_dfs.append(load_solexs(os.path.join(data_dir, f)))\n",
        "    except Exception as e:\n",
        "        print(f'Skipping {f}: {e}')\n",
        "\n",
        "for f in hel1os_files:\n",
        "    try:\n",
        "        hel1os_dfs.append(load_hel1os(os.path.join(data_dir, f)))\n",
        "    except Exception as e:\n",
        "        print(f'Skipping {f}: {e}')\n",
        "\n",
        "if not solexs_dfs or not hel1os_dfs:\n",
        "    print('WARNING: Missing files. Please upload both SoLEXS and HEL1OS files!')\n",
        "else:\n",
        "    all_solexs = pd.concat(solexs_dfs).sort_values('time').reset_index(drop=True)\n",
        "    all_hel1os = pd.concat(hel1os_dfs).sort_values('time').reset_index(drop=True)\n",
        "\n",
        "    print('Synchronizing timelines...')\n",
        "    fused_df = pd.merge_asof(all_solexs, all_hel1os, on='time', direction='nearest', tolerance=pd.Timedelta('2s'))\n",
        "    fused_df = fused_df.set_index('time').resample('1s').mean().ffill().dropna().reset_index()\n",
        "\n",
        "    print('Extracting physical features...')\n",
        "    fused_df['flux_ratio'] = fused_df['hard_flux'] / (fused_df['soft_flux'] + 1e-10)\n",
        "    fused_df['soft_rise'] = fused_df['soft_flux'].diff().fillna(0)\n",
        "    fused_df['hard_spike'] = fused_df['hard_flux'].diff().fillna(0)\n",
        "\n",
        "    threshold = fused_df['hard_spike'].quantile(0.95)\n",
        "    fused_df['is_flare'] = (fused_df['hard_spike'] > threshold).astype(int)\n",
        "    fused_df['flare_label'] = fused_df['is_flare'].shift(-900).fillna(0)\n",
        "\n",
        "    # Generating Master Flare Catalogue\n",
        "    flare_events = fused_df[fused_df['is_flare'] == 1][['time', 'soft_flux', 'hard_flux']].copy()\n",
        "    flare_events.to_csv('flare_catalogue.csv', index=False)\n",
        "    print(f'Saved Master Flare Catalogue with {len(flare_events)} events to flare_catalogue.csv')\n",
        "\n",
        "    print(f'Data fusion complete! Total rows: {fused_df.shape[0]}')\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Phase 2: LSTM Machine Learning Forecast Model"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "import json\n",
        "import torch\n",

        "import torch.nn as nn\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "from sklearn.preprocessing import MinMaxScaler\n",
        "\n",
        "class FlareDataset(Dataset):\n",
        "    def __init__(self, df, seq_length=60):\n",
        "        features = ['soft_flux', 'hard_flux', 'flux_ratio', 'soft_rise', 'hard_spike']\n",
        "        df = df.replace([np.inf, -np.inf], np.nan).fillna(0)\n",
        "        self.scaler = MinMaxScaler()\n",
        "        data = self.scaler.fit_transform(df[features].values)\n",
        "        X, y = [], []\n",
        "        if len(data) > seq_length:\n",
        "            for i in range(0, len(data) - seq_length, 10):\n",
        "                X.append(data[i:i+seq_length])\n",
        "                y.append(df.iloc[i+seq_length]['flare_label'])\n",
        "        self.X = torch.tensor(np.array(X), dtype=torch.float32)\n",
        "        self.y = torch.tensor(np.array(y), dtype=torch.long)\n",
        "\n",
        "    def __len__(self): return len(self.X)\n",
        "    def __getitem__(self, idx): return self.X[idx], self.y[idx]\n",
        "\n",
        "class FlareLSTM(nn.Module):\n",
        "    def __init__(self):\n",
        "        super().__init__()\n",
        "        self.lstm = nn.LSTM(5, 64, 2, batch_first=True)\n",
        "        self.fc = nn.Linear(64, 2)\n",
        "\n",
        "    def forward(self, x):\n",
        "        lstm_out, _ = self.lstm(x)\n",
        "        return self.fc(lstm_out[:, -1, :])\n",
        "\n",
        "if 'fused_df' in dir():\n",
        "    print('Preparing tensors...')\n",
        "    dataset = FlareDataset(fused_df)\n",
        "    loader = DataLoader(dataset, batch_size=256, shuffle=True)\n",
        "\n",
        "    model = FlareLSTM()\n",
        "    criterion = nn.CrossEntropyLoss()\n",
        "    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)\n",
        "\n",
        "    print('Training Deep Learning Model on 10-day dataset...')\n",
        "    model.train()\n",
        "    for epoch in range(5):\n",
        "        epoch_loss = 0.0\n",
        "        for X_batch, y_batch in loader:\n",
        "            optimizer.zero_grad()\n",
        "            output = model(X_batch)\n",
        "            loss = criterion(output, y_batch)\n",
        "            loss.backward()\n",
        "            optimizer.step()\n",
        "            epoch_loss += loss.item()\n",
        "        print(f'Epoch {epoch+1}, Loss: {epoch_loss/len(loader):.4f}')\n",
        "    print('Training Complete!')\n",
        "\n",
        "    model.eval()\n",
        "    with torch.no_grad():\n",
        "        last_sequence = dataset.X[-1].unsqueeze(0)\n",
        "        probs = torch.softmax(model(last_sequence), dim=1)\n",
        "        flare_prob = probs[0][1].item()\n",
        "\n",
        "    alert_data = {\n",
        "        'timestamp': str(fused_df['time'].iloc[-1]),\n",
        "        'flare_probability': flare_prob,\n",
        "        'alert_level': 'HIGH' if flare_prob > 0.7 else ('MEDIUM' if flare_prob > 0.4 else 'LOW'),\n",
        "        'lead_time_mins': 15,\n",
        "        'method': 'PyTorch LSTM Forecast (10-Day Authentic Fused)'\n",
        "    }\n",
        "    with open('flare_alerts.json', 'w') as f:\n",
        "        json.dump(alert_data, f, indent=4)\n",
        "    \n",
        "    # Save the trained model for the live backend inference\n",
        "    torch.save(model.state_dict(), 'solar_lstm.pth')\n",
        "    print('Saved trained model to solar_lstm.pth')\n",
        "\n",
        "    print('\\n--- DASHBOARD API JSON GENERATED ---')\n",
        "    print(json.dumps(alert_data, indent=2))\n"
      ]
    }
  ],
  "metadata": {
    "colab": {"provenance": []},
    "kernelspec": {"display_name": "Python 3", "name": "python3"},
    "language_info": {"name": "python"}
  },
  "nbformat": 4,
  "nbformat_minor": 0
}

output_path = r'v:\Desktop\Ekip_Bhaskar_CME_Event\Solar_Flare_Submission\Solar_Flare_ML_Pipeline.ipynb'
with open(output_path, 'w') as f:
    json.dump(notebook, f, indent=2)

print(f"Notebook written to: {output_path}")